# Example run
samples:
    176_ps8n_ET2323:  /fh/scratch/delete90/ha_g/Collaborator_Data/Broad_Terra/CRPC_patients-pdx_WGS/BAMs_symlink/176_ps8n_ET2323.bam
    189.3_ps3n_ET2405:  /fh/scratch/delete90/ha_g/Collaborator_Data/Broad_Terra/CRPC_patients-pdx_WGS/BAMs_symlink/189.3_ps3n_ET2405.bam
    15-003C1_NORMAL_MUSCLE:  /fh/scratch/delete90/ha_g/Collaborator_Data/Broad_Terra/CRPC_patients-pdx_WGS/BAMs_symlink/15-003C1_NORMAL_MUSCLE.bam
    13-117C1_NORMAL_MUSCLE:  /fh/scratch/delete90/ha_g/Collaborator_Data/Broad_Terra/CRPC_patients-pdx_WGS/BAMs_symlink/13-117C1_NORMAL_MUSCLE.bam    


# No white space when you concatenate with comma
# Must mention normal first and then tumor
groups:
    Lucap_176: 13-117C1_NORMAL_MUSCLE,176_ps8n_ET2323
    Lucap_189.3: 15-003C1_NORMAL_MUSCLE,189.3_ps3n_ET2405

# Labels can be used when you want to merge samples (e.g. If they are from same patients, such as different time points/metastatis)
# This can be done with labels argument. currently not being used in snakemake.
